# Generated by Django 4.1.13 on 2024-02-02 16:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_recording_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='recording_location',
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
