# Generated by Django 4.1.13 on 2024-02-15 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_recording_recording_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalAnnotations',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('start_time', models.IntegerField(blank=True, null=True)),
                ('end_time', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'recording',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.recording'
                    ),
                ),
                ('species', models.ManyToManyField(to='core.species')),
            ],
        ),
    ]
