# Generated by Django 4.1.13 on 2024-02-23 17:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_temporalannotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRTSCells',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('grts_cell_id', models.IntegerField()),
                ('sample_frame_id', models.IntegerField(blank=True, null=True)),
                (
                    'grts_geom',
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ('water_p', models.FloatField(blank=True, null=True)),
                ('outside_p', models.FloatField(blank=True, null=True)),
                ('location_1_type', models.CharField(blank=True, max_length=255, null=True)),
                ('location_1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_1_p', models.FloatField(blank=True, null=True)),
                ('location_2_type', models.CharField(blank=True, max_length=255, null=True)),
                ('location_2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_2_p', models.FloatField(blank=True, null=True)),
                ('sub_location_1_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_location_1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_location_1_p', models.FloatField(blank=True, null=True)),
                ('sub_location_2_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_location_2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_location_2_p', models.FloatField(blank=True, null=True)),
                ('own_1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('own_1_p', models.FloatField(blank=True, null=True)),
                ('priority_frame', models.BooleanField(blank=True, null=True)),
                ('priority_state', models.BooleanField(blank=True, null=True)),
                ('geom_4326', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('clipped', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recording',
            name='recorded_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
