# Generated by Django 4.1.13 on 2024-04-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recording_computed_species_recording_detector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrogram',
            name='colormap',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
