# Generated by Django 4.1.13 on 2024-12-02 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_alter_annotations_options_annotations_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='confidence',
            field=models.FloatField(
                default=1.0,
                help_text='A confidence value between 0 and 1.0, default is 1.0.',
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
