# Generated by Django 4.1.13 on 2024-12-17 17:57
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_annotations_options_annotations_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordingannotation",
            name="additional_data",
            field=models.JSONField(
                blank=True, help_text="Additional information about the models/data", null=True
            ),
        ),
    ]
