# Generated by Django 4.1.13 on 2025-03-26 21:22
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="run_inference_on_upload",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="configuration",
            name="spectrogram_view",
            field=models.CharField(
                choices=[("compressed", "Compressed"), ("uncompressed", "Uncompressed")],
                default="compressed",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="spectrogram_x_stretch",
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=3),
        ),
    ]
