# Generated by Django 4.1.13 on 2025-02-11 17:49

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcousticBatch',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('batch_id', models.BigIntegerField(unique=True)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                (
                    'recording_location',
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ('grts_cell_id', models.IntegerField(blank=True, null=True)),
                ('grts_cell', models.IntegerField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('software_name', models.TextField(blank=True, null=True)),
                ('software_developer', models.TextField(blank=True, null=True)),
                ('software_version', models.TextField(blank=True, null=True)),
                ('detector', models.TextField(blank=True, null=True)),
                ('species_list', models.TextField(blank=True, null=True)),
                ('unusual_occurrences', models.TextField(blank=True, null=True)),
                (
                    'computed_species',
                    models.ManyToManyField(
                        related_name='acousticbatch_computed_species', to='core.species'
                    ),
                ),
                (
                    'nabat_auto_species',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='acousticbatch_auto_species',
                        to='core.species',
                    ),
                ),
                (
                    'nabat_manual_species',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='acousticbatch_manual_species',
                        to='core.species',
                    ),
                ),
                (
                    'official_species',
                    models.ManyToManyField(
                        related_name='acousticbatch_official_species', to='core.species'
                    ),
                ),
            ],
            options={
                'verbose_name': 'NABat Acoustic Batch',
                'verbose_name_plural': 'NABat Acoustic Batches',
            },
        ),
        migrations.CreateModel(
            name='NABatSpectrogram',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('image_file', models.FileField(upload_to='')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('frequency_min', models.IntegerField()),
                ('frequency_max', models.IntegerField()),
                ('colormap', models.CharField(max_length=20, null=True)),
                (
                    'acoustic_batch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.acousticbatch'
                    ),
                ),
            ],
            options={
                'verbose_name': 'NABat Spectrogram',
                'verbose_name_plural': 'NABat Spectrograms',
            },
        ),
        migrations.CreateModel(
            name='NABatCompressedSpectrogram',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('image_file', models.FileField(upload_to='')),
                ('length', models.IntegerField()),
                (
                    'starts',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.IntegerField(), size=None
                        ),
                        size=None,
                    ),
                ),
                (
                    'stops',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.IntegerField(), size=None
                        ),
                        size=None,
                    ),
                ),
                (
                    'widths',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.IntegerField(), size=None
                        ),
                        size=None,
                    ),
                ),
                ('cache_invalidated', models.BooleanField(default=True)),
                (
                    'acoustic_batch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.acousticbatch'
                    ),
                ),
                (
                    'spectrogram',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.nabatspectrogram'
                    ),
                ),
            ],
            options={
                'verbose_name': 'NABat Compressed Spectrogram',
                'verbose_name_plural': 'NABat Compressed Spectrogram',
            },
        ),
        migrations.CreateModel(
            name='AcousticBatchAnnotation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('comments', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                (
                    'confidence',
                    models.FloatField(
                        default=1.0,
                        help_text='A confidence value between 0 and 1.0, default is 1.0.',
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    'additional_data',
                    models.JSONField(
                        blank=True,
                        help_text='Additional information about the models/data',
                        null=True,
                    ),
                ),
                (
                    'acoustic_batch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.acousticbatch'
                    ),
                ),
                ('species', models.ManyToManyField(to='core.species')),
            ],
            options={
                'verbose_name': 'NABat Acoustic Batch Annotation',
                'verbose_name_plural': 'NABat Acoustic Batch Annotations',
            },
        ),
    ]
