# Generated by Django 4.1.13 on 2025-04-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_configuration_run_inference_on_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='default_color_scheme',
            field=models.CharField(
                choices=[
                    ('inferno', 'Inferno'),
                    ('cividis', 'Cividis'),
                    ('viridis', 'Viridis'),
                    ('magma', 'Magma'),
                    ('turbo', 'Turbo'),
                    ('plasma', 'Plasma'),
                ],
                default='inferno',
                max_length=20,
            ),
        ),
    ]
