# Generated by Django 4.1.13 on 2025-04-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ('core', '0015_configuration_default_color_scheme'),
        ('core', '0016_configuration_default_spectrogram_background_color'),
    ]

    dependencies = [
        ('core', '0014_configuration_run_inference_on_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='default_color_scheme',
            field=models.CharField(
                choices=[
                    ('inferno', 'Inferno'),
                    ('cividis', 'Cividis'),
                    ('viridis', 'Viridis'),
                    ('magma', 'Magma'),
                    ('turbo', 'Turbo'),
                    ('plasma', 'Plasma'),
                ],
                default='inferno',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='configuration',
            name='default_spectrogram_background_color',
            field=models.CharField(default='rgb(0, 0, 0)', max_length=18),
        ),
    ]
