# Generated by Django 4.1.13 on 2025-04-11 15:03
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_nabatrecording_processingtask_nabatspectrogram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="common_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="family",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="genus",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="species",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="species_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="species_code_6",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
