# Generated by Django 4.1.13 on 2025-05-02 20:43
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_alter_species_common_name_alter_species_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='default_color_scheme',
            field=models.CharField(
                choices=[
                    ('inferno', 'Inferno'),
                    ('cividis', 'Cividis'),
                    ('viridis', 'Viridis'),
                    ('magma', 'Magma'),
                    ('turbo', 'Turbo'),
                    ('plasma', 'Plasma'),
                ],
                default='inferno',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='configuration',
            name='default_spectrogram_background_color',
            field=models.CharField(default='rgb(0, 0, 0)', max_length=18),
        ),
    ]
