# Generated by Django 4.2.23 on 2025-08-15 12:55
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_species_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grtscells',
            name='clipped',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='location_1_name',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='location_1_p',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='location_1_type',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='location_2_name',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='location_2_p',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='location_2_type',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='outside_p',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='own_1_name',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='own_1_p',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='priority_frame',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='priority_state',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='sub_location_1_name',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='sub_location_1_p',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='sub_location_1_type',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='sub_location_2_name',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='sub_location_2_p',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='sub_location_2_type',
        ),
        migrations.RemoveField(
            model_name='grtscells',
            name='water_p',
        ),
    ]
