# Generated by Django 4.2.23 on 2025-08-20 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_remove_grtscells_clipped_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemporalAnnotations',
            new_name='SequenceAnnotations',
        ),
    ]
