# Generated by Django 4.2.23 on 2025-09-29 21:15

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_temporalannotations_sequenceannotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='NABatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('session_token', models.UUIDField()),
                ('api_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('user_id', models.TextField(null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'NABat Session',
                'verbose_name_plural': 'NABat Sessions',
            },
        ),
    ]
