# Generated by Django 4.2.23 on 2025-11-11 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_rename_temporalannotations_sequenceannotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingTag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('text', models.CharField(max_length=50)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='recording',
            name='tag',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.recordingtag'
            ),
        ),
        migrations.AddConstraint(
            model_name='recordingtag',
            constraint=models.UniqueConstraint(
                fields=('user', 'text'), name='unique_user_text_tag'
            ),
        ),
    ]
