# Generated by Django 4.2.23 on 2025-12-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_recordingtag_recording_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='mark_annotations_completed_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='non_admin_upload_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='show_my_recordings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recordingannotation',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
