# Generated by Django 4.2.23 on 2025-11-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_recordingtag_recording_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='tag',
        ),
        migrations.AddField(
            model_name='recording',
            name='tags',
            field=models.ManyToManyField(to='core.recordingtag'),
        ),
    ]
