# Generated by Django 4.2.23 on 2025-12-05 19:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_spectrogramsvg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedPulseAnnotation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('contours', models.JSONField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recording')),
            ],
        ),
    ]
