# Generated by Django 4.2.23 on 2025-12-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_configuration_mark_annotations_completed_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingannotation',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
