# Generated by Django 4.2.23 on 2026-02-03 12:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_configuration_mark_annotations_completed_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='high_freq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='low_freq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compressedspectrogram',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='compressedspectrogram',
            name='starts',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), size=None
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name='compressedspectrogram',
            name='stops',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), size=None
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name='compressedspectrogram',
            name='widths',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), size=None
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name='nabatcompressedspectrogram',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nabatcompressedspectrogram',
            name='starts',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), size=None
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name='nabatcompressedspectrogram',
            name='stops',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), size=None
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name='nabatcompressedspectrogram',
            name='widths',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), size=None
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name='nabatspectrogram',
            name='duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nabatspectrogram',
            name='frequency_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nabatspectrogram',
            name='frequency_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sequenceannotations',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequenceannotations',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='frequency_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='frequency_min',
            field=models.FloatField(),
        ),
    ]
