# Generated by Django 4.2.23 on 2026-01-29 14:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0026_alter_annotations_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseMetadata',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('index', models.IntegerField()),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('contours', models.JSONField()),
                (
                    'recording',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.recording'
                    ),
                ),
            ],
        ),
    ]
