# Generated by Django 4.2.23 on 2026-01-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0027_pulsemetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrogramimage',
            name='type',
            field=models.CharField(
                choices=[
                    ('spectrogram', 'Spectrogram'),
                    ('compressed', 'Compressed'),
                    ('masks', 'Masks'),
                ],
                default='spectrogram',
                max_length=20,
            ),
        ),
    ]
