# Generated by Django 4.2.23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0027_alter_annotations_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsemetadata',
            name='contours',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
