# Generated by Django 4.2.23 on 2026-01-30 17:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0028_alter_spectrogramimage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsemetadata',
            name='char_freq',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='pulsemetadata',
            name='curve',
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name='pulsemetadata',
            name='heel',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='pulsemetadata',
            name='knee',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
