# Generated by Django 5.2.11

from django.db import migrations, models

# Generic species codes that are "multiple" (were individual in old fixture)
GENERIC_MULTIPLE_CODES = ('NYSP', 'MYSP', 'LESP')


def update_species_category_labels(apps, schema_editor):
    """Update category values to match species.json: individual→single, couplet→multiple."""
    Species = apps.get_model('core', 'Species')
    # NoID: by common_name or species_code NoBat
    Species.objects.filter(common_name='Code used for surveys that recorded 0 bats').update(
        category='noid'
    )
    Species.objects.filter(species_code='NoBat').update(category='noid')
    # Generic labels NYSP, MYSP, LESP → multiple (before individual→single)
    Species.objects.filter(species_code__in=GENERIC_MULTIPLE_CODES).update(category='multiple')
    # Remaining individual → single
    Species.objects.filter(category='individual').update(category='single')
    # couplet → multiple
    Species.objects.filter(category='couplet').update(category='multiple')


def reverse_species_category_labels(apps, schema_editor):
    """Revert category values to previous labels."""
    Species = apps.get_model('core', 'Species')
    # multiple: generic codes back to individual, rest to couplet
    Species.objects.filter(species_code__in=GENERIC_MULTIPLE_CODES).update(category='individual')
    Species.objects.filter(category='multiple').update(category='couplet')
    Species.objects.filter(category='single').update(category='individual')
    Species.objects.filter(common_name='Code used for surveys that recorded 0 bats').update(
        category='individual'
    )
    Species.objects.filter(species_code='NoBat').update(category='individual')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0030_userprofile'),
    ]

    operations = [
        migrations.RunPython(update_species_category_labels, reverse_species_category_labels),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.CharField(
                choices=[
                    ('single', 'Single Species'),
                    ('multiple', 'Multiple Species'),
                    ('frequency', 'Frequency'),
                    ('noid', 'NoID'),
                ],
                default='single',
                help_text='Category label: single species, multiple species, frequency, or NoID',
                max_length=20,
            ),
        ),
    ]
