# Generated by Django 5.2.11 on 2026-02-13 19:47

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('core', 'UserProfile')

    for user in User.objects.all():
        profile, created = UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_code=migrations.RunPython.noop),
    ]
