# Generated by Django 5.2.11 on 2026-02-26 17:07
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_species_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulsemetadata",
            name="slopes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
