# Generated by Django 6.0.3 on 2026-03-16 19:07
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_recording_annotation_species_through"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spectrogramimage",
            name="type",
            field=models.CharField(
                choices=[
                    ("spectrogram", "Spectrogram"),
                    ("compressed", "Compressed"),
                    ("masks", "Masks"),
                    ("waveform_compressed", "Waveform Compressed"),
                    ("waveform_uncompressed", "Waveform Uncompressed"),
                ],
                default="spectrogram",
                max_length=128,
            ),
        ),
    ]
