# Generated by Django 6.0.3 on 2026-04-08 13:29
from __future__ import annotations

import json
from pathlib import Path

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import GEOSGeometry
from django.db import migrations, models
import django.db.models.deletion

DEFAULT_GEOJSON = settings.BASE_DIR / "bats_ai" / "core" / "data" / "species-ranges.geojson"


def load_species_ranges_from_default_geojson(apps, schema_editor) -> None:
    Species = apps.get_model("core", "Species")
    SpeciesRange = apps.get_model("core", "SpeciesRange")

    path = Path(DEFAULT_GEOJSON).resolve()
    if not path.is_file():
        raise FileNotFoundError(f"GeoJSON file not found: {path}")

    doc = json.loads(path.read_text(encoding="utf-8"))
    if doc.get("type") != "FeatureCollection":
        raise ValueError('Expected a GeoJSON FeatureCollection ("type": "FeatureCollection").')

    features = doc.get("features") or []
    for feature in features:
        props = feature.get("properties") or {}
        code = props.get("name")
        if not code or not str(code).strip():
            continue
        code = str(code).strip().upper()

        geom_json = feature.get("geometry")
        if not geom_json:
            continue

        geom = GEOSGeometry(json.dumps(geom_json))
        if geom.srid in (None, 0):
            geom.srid = 4326
        elif geom.srid != 4326:
            geom.transform(4326)

        species = Species.objects.filter(species_code__iexact=code).first()
        if species is None:
            continue

        fid = props.get("id")
        source_feature_id = str(fid) if fid is not None else ""
        SpeciesRange.objects.update_or_create(
            species=species,
            defaults={
                "geom": geom,
                "source_feature_id": source_feature_id,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_add_grtscells_centroid_4326"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recording",
            old_name="grts_cell",
            new_name="sample_frame_id",
        ),
        migrations.CreateModel(
            name="SpeciesRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                (
                    "source_feature_id",
                    models.CharField(
                        blank=True,
                        help_text=("Optional id from the source GeoJSON feature properties."),
                        max_length=255,
                    ),
                ),
                (
                    "species",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="range",
                        to="core.species",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            load_species_ranges_from_default_geojson,
            migrations.RunPython.noop,
        ),
    ]
