# Generated by Django 6.0.3 on 2026-04-02 17:19
from __future__ import annotations

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_add_grtscells_centroid_4326"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recording",
            old_name="grts_cell",
            new_name="sample_frame_id",
        ),
        migrations.CreateModel(
            name="SpeciesRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                (
                    "source_feature_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional id from the source GeoJSON feature properties.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "species",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="range",
                        to="core.species",
                    ),
                ),
            ],
        ),
    ]
