# Generated by Django 6.0.4 on 2026-04-24 13:01

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_species_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grtscells",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
