# Generated by Django 4.2.23 on 2026-06-11 00:00
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_grtscells_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="create_pulse_annotations_from_batbot",
            field=models.BooleanField(default=False),
        ),
    ]
