# Generated by Django 6.0.7 on 2026-08-05 18:56

from __future__ import annotations

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_grtscells_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nabatrecording",
            old_name="grts_cell",
            new_name="sample_frame_id",
        ),
        migrations.CreateModel(
            name="NABatPulseMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("index", models.IntegerField()),
                ("bounding_box", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ("contours", models.JSONField(blank=True, null=True)),
                (
                    "curve",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "char_freq",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "knee",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "heel",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("slopes", models.JSONField(blank=True, null=True)),
                (
                    "nabat_recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.nabatrecording"
                    ),
                ),
            ],
        ),
    ]
