# Generated by Django 6.0.7 on 2026-08-10 18:29

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_rename_grts_cell_nabatrecording_sample_frame_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="create_pulse_annotations_from_batbot",
            field=models.BooleanField(default=False),
        ),
    ]
