# Generated by Django 6.0.7 on 2026-10-01 15:14

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_configuration_create_pulse_annotations_from_batbot"),
    ]

    operations = [
        migrations.CreateModel(
            name="NABatRecordingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("nabat_file_list_id", models.BigIntegerField(unique=True)),
                ("nabat_project_id", models.BigIntegerField(blank=True, null=True)),
                ("created_by_email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name": "NABat File List",
                "verbose_name_plural": "NABat File Lists",
            },
        ),
        migrations.CreateModel(
            name="NABatRecordingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("recording_time", models.DateTimeField(blank=True, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("recording_id", models.BigIntegerField()),
                (
                    "nabat_recording",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="list_items",
                        to="core.nabatrecording",
                    ),
                ),
                (
                    "recording_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.nabatrecordinglist",
                    ),
                ),
            ],
            options={
                "verbose_name": "NABat File List Item",
                "verbose_name_plural": "NABat File List Items",
                "ordering": ["-recording_time", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recording_list", "recording_id"), name="recording_once_per_list"
                    )
                ],
            },
        ),
    ]
