name: CD
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  release:
    types:
      - published
concurrency:
  # Only run the latest workflow.
  # If a build is already happening, cancel it to avoid a race
  # condition where an older image overwrites a newer one.
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    name: Build [batai]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [server, client]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate image tags
        uses: docker/metadata-action@v5
        id: image-tags
        with:
          images:
            ghcr.io/Kitware/batai/${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ matrix.image == 'server' && 'dev/django.Dockerfile' || 'dev/client.Dockerfile' }}
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.image-tags.outputs.result }}
